// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADTp9lU9lm_YpicxEf8AxEFvqvhZNLN04',
    appId: '1:742437085211:web:cb61101c56bd6310e698be',
    messagingSenderId: '742437085211',
    projectId: 'projectebook-e07e4',
    authDomain: 'projectebook-e07e4.firebaseapp.com',
    storageBucket: 'projectebook-e07e4.appspot.com',
    measurementId: 'G-XYF3TGHGW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK3klj5BB_jtKQ0bOCPWY-YLlWCSV31vA',
    appId: '1:742437085211:android:f22aa7a3962da7c2e698be',
    messagingSenderId: '742437085211',
    projectId: 'projectebook-e07e4',
    storageBucket: 'projectebook-e07e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQp7gjGPLHZYfI5pTsts65iP63AV_uto4',
    appId: '1:742437085211:ios:18df1d9684326f97e698be',
    messagingSenderId: '742437085211',
    projectId: 'projectebook-e07e4',
    storageBucket: 'projectebook-e07e4.appspot.com',
    iosBundleId: 'com.example.projectEbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQp7gjGPLHZYfI5pTsts65iP63AV_uto4',
    appId: '1:742437085211:ios:18df1d9684326f97e698be',
    messagingSenderId: '742437085211',
    projectId: 'projectebook-e07e4',
    storageBucket: 'projectebook-e07e4.appspot.com',
    iosBundleId: 'com.example.projectEbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADTp9lU9lm_YpicxEf8AxEFvqvhZNLN04',
    appId: '1:742437085211:web:3c1d4b6c3048c0b6e698be',
    messagingSenderId: '742437085211',
    projectId: 'projectebook-e07e4',
    authDomain: 'projectebook-e07e4.firebaseapp.com',
    storageBucket: 'projectebook-e07e4.appspot.com',
    measurementId: 'G-QDL1WL4P4G',
  );
}
